name: Publish NuGet

on:
  push:
    branches: 
    - main

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: RacoonSecure/RacoonSecure.Core
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      
      - name: Install dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --configuration Release --no-restore
    
      - name: Run Tests
        id: run_tests
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: RacoonSecure/RacoonSecure.Core.Tests/RacoonSecure.Core.Tests.csproj
          report_name: RacoonSecure.Core.Tests
          report_title: RacoonSecure Core Tests
          github_token: ${{ secrets.GITHUB_TOKEN }}
          set_check_status_from_test_outcome: true    

      - name: Fail job on failed tests
        run: exit 1 
        if: steps.run_tests.outputs.result_value == 'Failed'          

      - name: Publish RacoonSecure.Core NuGet
        id: nuget_publish_core
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: RacoonSecure/RacoonSecure.Core/RacoonSecure.Core.csproj
          VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
          TAG_FORMAT: '*'
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - name: Publish RacoonSecure.Identity NuGet
        id: nuget_publish_identity
        uses: brandedoutcast/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: RacoonSecure/RacoonSecure.Identity/RacoonSecure.Identity.csproj
          VERSION_REGEX: '^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$'
          TAG_FORMAT: '*'
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: steps.nuget_publish_core.outputs.PACKAGE_PATH != ''      
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.nuget_publish_core.outputs.VERSION }}"
          prerelease: false
          title: "RacoonSecure.Core"
          files: |
            ${{ steps.nuget_publish_core.outputs.PACKAGE_PATH }}
            *.zip

      - uses: "marvinpinto/action-automatic-releases@latest"
        if: steps.nuget_publish_identity.outputs.PACKAGE_PATH != ''      
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.nuget_publish_identity.outputs.VERSION }}"
          prerelease: false
          title: "RacoonSecure.Identity"
          files: |
            ${{ steps.nuget_publish_identity.outputs.PACKAGE_PATH }}
            *.zip
      